sudo: false
dist: trusty
group: edge

language: java
jdk: oraclejdk9

notifications:
  email:
    on_success: always
    on_failure: never

before_install:
- mkdir pro
- cd pro
- wget -d -v --no-check-certificate https://github.com/forax/pro/releases/download/v0.9.160/pro-9-b160-linux.tar.gz
- tar -xzf pro-9-b160-linux.tar.gz
- ls -la
- cd ..
- tree

install:
- java -version

script:
- ./pro/bin/pro
