sudo: false
dist: trusty
language: java

install:
- wget --no-check-certificate https://github.com/forax/pro/releases/download/v0.9.167/pro-9-b167-linux.tar.gz
- tar -xzf pro-9-b167-linux.tar.gz
- wget --no-check-certificate -O jupiter.jar http://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.0.0-M4/junit-platform-console-standalone-1.0.0-M4.jar

script:
- ./pro/bin/pro
- java -ea -classpath jupiter.jar:target/test/exploded/de.sormuras.beethoven org.junit.platform.console.ConsoleLauncher --scan-classpath
