sudo: required
dist: precise
group: edge

before_install:
  - chmod +x gradlew

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

language:
  java
  
jdk:
  - oraclejdk9

notifications:
  email:
    on_success: always # [always|never|change] # default: change
    on_failure: always # [always|never|change] # default: always

# after_success:
#   - bash <(curl -s https://codecov.io/bash)
