sudo: false
dist: trusty
language: java

notifications:
  email:
    on_success: always
    on_failure: always

install:
# Download pro release and use it...
#- wget --no-check-certificate https://github.com/forax/pro/releases/download/v0.9.167/pro-9-b167-linux.tar.gz
#- tar -xzf pro-9-b167-linux.tar.gz
#- alias pro="~/pro/bin/pro"

# Download jdk-9 "manually"
- pwd
- wget http://download.java.net/java/jdk9/archive/168/binaries/jdk-9-ea+168_linux-x64_bin.tar.gz
- gunzip jdk-9-ea+168_linux-x64_bin.tar.gz
- tar x -f jdk-9-ea+168_linux-x64_bin.tar
- ls -la
- chown -R travis:travis ~/jdk-9
- ls -la
- export JAVA_HOME=~/jdk-9
- PATH=$JAVA_HOME/bin:$PATH
- ls -la ~/jdk-9/bin
- javac -version

# Download pro source and build it... (needs latest jdk-9)
- wget --no-check-certificate https://github.com/forax/pro/archive/master.zip
- unzip master.zip
- cd pro-master
- chmod u+x build.sh
- ./build.sh
- cd ..
- alias pro="~/pro-master/target/pro/bin/pro"
- pro version

script:
- cd .pro
- pro
